services:
  - type: web
    name: keeper-app
    env: node
    rootDir: backend
    buildCommand: |
      cd ../frontend
      npm install
      npm run build
      cd ../backend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: your-mongo-uri
